### ISSUE TITLE
Figure out how to increase heroku "memory"

### ISSUE THREAD

**Issue by alexdanilowicz** [alexdanilowicz/server-leftonread#5]
Right now, if chat.db is more than 200MB, there's a problem.

Research how to remedy this issue. Would more dynos solve it? Or are dynos different?

**Comment by alexdanilowicz** [comment]
Response from Heroku:

**Comment by Teddarific** [comment]
Here's how we can actually run a test:

1) Get a very large chat.db
2) Upload it
3) Save the key, and query the API manually for the instance associated with the key
4) Look at the logs to see where it was halted. If I remember correctly, it gets halted at "Querying database..." which leads me to believe the server doesn't have enough RAM to handle the in-memory processing we want to do

**Comment by alexdanilowicz** [comment]
Latest Heroku response:

You can view your ticket and add additional comments at https://help.heroku.com/tickets/593950

Hi Alexander,
Free and Hobby dynos have 512Mb available. You can get the full listing here: https://devcenter.heroku.com/articles/dyno-types

Those log messages are indicating that you have used too much memory (709Mb), which triggers the R14 error.

Take care.
